[package]
name = "migration"
version = "2.0.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"

[dependencies]
util = {path = "../util"}
error-chain = "0.12.4"
kvm-ioctls = "0.6.0"
lazy_static = "1.4.0"
serde = { version = ">=1.0.114", features = ["derive"] }
serde_json = "1.0.55"

[dev-dependencies]
migration_derive = { path = "../migration_derive" }