[package]
name = "StratoVirt"
version = "0.3.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
description = "a lightweight hypervisor with low memory overhead and fast booting speed"
license = "Mulan PSL v2"

[dependencies]
error-chain = "0.12.4"
kvm-ioctls = "0.6.0"
libc = "0.2.71"
log = "0.4.8"
vmm-sys-util = "0.7.0"
machine = { path = "machine" }
machine_manager = { path = "machine_manager" }
util = { path = "util" }
virtio = { path = "virtio" }

[workspace]
members = [
    "address_space",
    "boot_loader",
    "cpu",
    "devices",
    "machine",
    "machine_manager",
    "pci",
    "sysbus",
    "util",
    "virtio",
]

[[bin]]
name = "stratovirt"
path = "src/main.rs"

[features]
default = []

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
stratovirt = { path = "/usr/bin/stratovirt" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
