[package]
name = "StratoVirt"
version = "0.2.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
description = "a lightweight hypervisor with low memory overhead and fast booting speed"
license = "Mulan PSL v2"

[dependencies]
error-chain = "0.12.4"
libc = "0.2.71"
log = "0.4.8"
vmm-sys-util = "0.7.0"
machine_manager = { path = "machine_manager" }
micro_vm = { path = "micro_vm" }
util = { path = "util" }
virtio = { path = "virtio" }

[workspace]
members = [
    "address_space",
    "boot_loader",
    "cpu",
    "devices",
    "machine_manager",
    "micro_vm",
    "mmio",
    "util",
    "virtio",
]

[[bin]]
name = "stratovirt"
path = "src/main.rs"

[features]
default = []

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
stratovirt = { path = "/usr/bin/stratovirt" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
