[package]
name = "cpu"
version = "0.3.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
license = "Mulan PSL v2"
description = "CPU emulation"

[dependencies]
error-chain = "0.12.4"
kvm-bindings = ">=0.3.0"
kvm-ioctls = "0.6.0"
log = "0.4.8"
libc = ">=0.2.71"
vmm-sys-util = ">=0.7.0"
hypervisor = { path = "../hypervisor" }
machine_manager = { path = "../machine_manager" }
util = { path = "../util" }

[dev-dependencies]
serial_test = "0.5.1"
