[package]
name = "util"
version = "0.1.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
license = "Mulan PSL v2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.71"
log = { version = "0.4.8", features = ["std"]}
error-chain = "0.12.4"
kvm-bindings = "0.3.0"
kvm-ioctls = { git = "https://github.com/rust-vmm/kvm-ioctls", branch = "master" }
vmm-sys-util = "0.6.1"
