[package]
name = "util"
version = "2.0.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
license = "Mulan PSL v2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
kvm-bindings = ">=0.3.0"
kvm-ioctls = "0.6.0"
libc = ">=0.2.71"
log = { version = "0.4.8", features = ["std"]}
vmm-sys-util = ">=0.7.0"
lazy_static = "1.4.0"
byteorder = "1.3.4"
