[package]
name = "devices"
version = "2.2.0"
authors = ["Huawei StratoVirt Team"]
edition = "2021"
license = "Mulan PSL v2"

[dependencies]
error-chain = "0.12.4"
libc = "0.2"
log = "0.4"
kvm-ioctls = ">=0.11.0"
serde = { version = "1.0", features = ["derive"] }
vmm-sys-util = ">=0.10.0"
byteorder = "1.4.3"
kvm-bindings = { version = ">=0.5.0", features = ["fam-wrappers"] }
address_space = { path = "../address_space" }
hypervisor = { path = "../hypervisor" }
machine_manager = { path = "../machine_manager" }
migration = { path = "../migration" }
migration_derive = { path = "../migration_derive" }
sysbus = { path = "../sysbus" }
util = { path = "../util" }
acpi = { path = "../acpi" }

[dev-dependencies]
serial_test = "0.5.1"

[features]
default = []
