[package]
name = "devices"
version = "0.3.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
license = "Mulan PSL v2"

[dependencies]
error-chain = "0.12.4"
libc = ">=0.2.71"
log = "0.4.8"
kvm-ioctls = "0.6.0"
serde = { version = ">=1.0.114", features = ["derive"] }
vmm-sys-util = ">=0.7.0"
address_space = { path = "../address_space" }
boot_loader = { path = "../boot_loader" }
hypervisor = { path = "../hypervisor" }
machine_manager = { path = "../machine_manager" }
sysbus = { path = "../sysbus" }
util = { path = "../util" }
acpi = { path = "../acpi" }
byteorder = "1.3.4"
kvm-bindings = ">=0.3.0"

[dev-dependencies]
serial_test = "0.5.1"

[features]
default = []
