[package]
name = "machine_manager"
version = "0.3.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
license = "Mulan PSL v2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
log = "0.4.8"
libc = "0.2.71"
serde_json = "1.0.55"
vmm-sys-util = "0.7.0"
util = { path = "../util" }
serde = { version = "1.0.114", features = ["derive"] }

[features]
default = []

