[package]
name = "machine"
version = "2.0.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
license = "Mulan PSL v2"
description = "Emulation machines"

[dependencies]
error-chain = "0.12.4"
kvm-bindings = ">=0.3.0"
kvm-ioctls = "0.6.0"
log = "0.4.8"
libc = ">=0.2.71"
serde = { version = ">=1.0.114", features = ["derive"] }
serde_json = "1.0.55"
vmm-sys-util = ">=0.7.0"
vfio-bindings = "0.2.0"
acpi = { path = "../acpi" }
address_space = { path = "../address_space" }
boot_loader = { path = "../boot_loader" }
cpu = { path = "../cpu" }
devices = { path = "../devices" }
hypervisor = { path = "../hypervisor" }
machine_manager = { path = "../machine_manager" }
migration = { path = "../migration" }
pci = { path = "../pci" }
sysbus = { path = "../sysbus" }
util = { path = "../util" }
virtio = { path = "../virtio" }
vfio = { path = "../vfio" }

[features]
default = ["qmp"]
qmp = []
