[package]
name = "vnc"
version = "2.2.0"
authors = ["Huawei StratoVirt Team"]
edition = "2021"
license = "Mulan PSL v2"
description = "Visual Network Computing"

[dependencies]
byteorder = "1.3.4"
thiserror = "1.0"
anyhow = "1.0"
libc = ">=0.2.71"
log = "0.4.8"
serde_json = "1.0.55"
vmm-sys-util = ">=0.7.0"
once_cell = "1.9.0"
sscanf = "0.2.1"
bitintr = "0.2.0"
usb = { path = "../usb" }
address_space = { path = "../address_space" }
hypervisor = { path = "../hypervisor" }
machine_manager = { path = "../machine_manager" }
migration = { path = "../migration" }
migration_derive = { path = "../migration_derive" }
sysbus = { path = "../sysbus" }
util = { path = "../util" }
pci = { path = "../pci" }
acpi = { path = "../acpi" }