[package]
name = "address_space"
version = "0.1.0"
authors = ["Huawei StratoVirt Team"]
license = "Mulan PSL v2"
description = "provide memory management for VM"

[dependencies]
util = {path = "../util"}

kvm-ioctls = "0.5.0"
libc = "0.2.71"
kvm-bindings = "0.2.0"
vmm-sys-util = "0.6.1"
error-chain = "0.12.4"
log = "0.4.8"
