[package]
name = "boot_loader"
version = "0.1.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
license = "Mulan PSL v2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
address_space = { path = "../address_space" }
util = { path = "../util" }

kvm-bindings = "0.2.0"
kvm-ioctls = "0.5.0"
vmm-sys-util = "0.6.1"

libc = "0.2.71"
log = "0.4.8"
error-chain = "0.12.4"
