[package]
name = "ozone"
version = "0.1.0"
authors = ["Huawei StratoVirt Team"]
edition = "2018"
description = "Provides protection for stratovirt"
license = "Mulan PSL v2"

[dependencies]
error-chain = "0.12.4"
libc = ">=0.2.71"

util = { path = "../util" }